Search.appendIndex(
    [
                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Manager",
            "name": "Block_Manager",
            "summary": "Intercepts\u0020\u0027the\u0020content\u0027\u0020filter\u0020to\u0020allow\u0020overriding\u0020of\u0020the\u0020rendering\u0020functions\nof\u0020Gutenberg\u0020blocks.\u0020This\u0020allows\u0020us\u0020to\u0020use\u0020twig\u0020for\u0020block\u0020rendering.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Manager.html"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Manager\u003A\u003Adetermine_block_type_class\u0028\u0029",
            "name": "determine_block_type_class",
            "summary": "Attempts\u0020to\u0020create\u0020a\u0020custom\u0020block\u0020from\u0020class\u0020from\u0020a\u0020block.\u0020Falls\u0020back\nto\u0020a\u0020default\u0020Clarkson\u0020Core\u0020block\u0020type.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Manager.html#method_determine_block_type_class"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Manager\u003A\u003Asanitize_block_type_name\u0028\u0029",
            "name": "sanitize_block_type_name",
            "summary": "Filters\u0020a\u0020block\u0020name\u0020into\u0020a\u0020valid\u0020class\u0020name.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Manager.html#method_sanitize_block_type_name"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Type",
            "name": "Block_Type",
            "summary": "This\u0020custom\u0020block\u0020overwrites\u0020the\u0020render\u0020callback\u0020to\u0020use\u0020twig\u0020files.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Type.html"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Type\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Replaces\u0020the\u0020original\u0020block\u0020render\u0020function,\u0020and\u0020saves\u0020the\u0020original\u0020render\nfunction\u0020in\u0020case\u0020we\u0020can\u0027t\u0020find\u0020a\u0020fitting\u0020twig\u0020file.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Type.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Type\u003A\u003Aget_twig_template_path\u0028\u0029",
            "name": "get_twig_template_path",
            "summary": "Allows\u0020filtering\u0020of\u0020the\u0020path\u0020where\u0020this\u0020blocks\u0020twig\u0020file\u0020is\u0020found.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Type.html#method_get_twig_template_path"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg\\Block_Type\u003A\u003Aclarkson_render_callback\u0028\u0029",
            "name": "clarkson_render_callback",
            "summary": "Tries\u0020to\u0020find\u0020a\u0020twig\u0020file\u0020to\u0020use\u0020for\u0020rendering.\u0020If\u0020the\u0020twig\u0020file\u0020doesn\u0027t\nexists\u0020it\u0020falls\u0020back\u0020to\u0020the\u0020original\u0020render\u0020callback.",
            "url": "classes/Clarkson-Core-Gutenberg-Block-Type.html#method_clarkson_render_callback"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects",
            "name": "Objects",
            "summary": "This\u0020class\u0020is\u0020used\u0020to\u0020convert\u0020WordPress\u0020posts,\u0020terms\u0020and\u0020users\u0020into\u0020Clarkson\nObjects.",
            "url": "classes/Clarkson-Core-Objects.html"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_terms\u0028\u0029",
            "name": "get_terms",
            "summary": "Convert\u0020WP_Term\u0020object\u0020to\u0020a\u0020Clarkson\u0020Object.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_terms"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_term\u0028\u0029",
            "name": "get_term",
            "summary": "Get\u0020term\u0020data.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_term"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_users\u0028\u0029",
            "name": "get_users",
            "summary": "Convert\u0020WP_User\u0020object\u0020to\u0020a\u0020Clarkson\u0020Object.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_users"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_user\u0028\u0029",
            "name": "get_user",
            "summary": "Get\u0020user\u0020by\u0020user\u0020id.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_user"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_objects\u0028\u0029",
            "name": "get_objects",
            "summary": "Get\u0020an\u0020array\u0020of\u0020posts\u0020converted\u0020to\u0020their\u0020corresponding\u0020WordPress\u0020object\u0020class.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_objects"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_object\u0028\u0029",
            "name": "get_object",
            "summary": "Get\u0020post\u0020that\u0027s\u0020converted\u0020to\u0020their\u0020corresponding\u0020WordPress\u0020object\u0020class.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_object"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_roles\u0028\u0029",
            "name": "get_roles",
            "summary": "Get\u0020an\u0020array\u0020of\u0020roles\u0020converted\u0020from\u0020their\u0020corresponding\u0020WordPress\u0020role\u0020class.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_roles"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_role\u0028\u0029",
            "name": "get_role",
            "summary": "Get\u0020Clarkson\u0020role\u0020object\u0020by\u0020WordPress\u0020role\u0020object.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_role"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_template\u0028\u0029",
            "name": "get_template",
            "summary": "",
            "url": "classes/Clarkson-Core-Objects.html#method_get_template"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_templates\u0028\u0029",
            "name": "get_templates",
            "summary": "Get\u0020an\u0020array\u0020of\u0020posts\u0020converted\u0020to\u0020their\u0020corresponding\u0020WordPress\u0020template\u0020class.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_templates"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_post_types\u0028\u0029",
            "name": "get_post_types",
            "summary": "Get\u0020an\u0020array\u0020of\u0020post\u0020types\u0020converted\u0020from\u0020their\u0020corresponding\u0020WordPress\u0020post\u0020type\u0020class.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_post_types"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_post_type\u0028\u0029",
            "name": "get_post_type",
            "summary": "Get\u0020post\u0020type\u0020object\u0020by\u0020post\u0020type.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_post_type"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_taxonomies\u0028\u0029",
            "name": "get_taxonomies",
            "summary": "Get\u0020an\u0020array\u0020of\u0020taxonomies\u0020converted\u0020from\u0020their\u0020corresponding\u0020WordPress\u0020taxonomy\u0020class.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_taxonomies"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_taxonomy\u0028\u0029",
            "name": "get_taxonomy",
            "summary": "Get\u0020taxonomy\u0020object\u0020by\u0020taxonomy.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_taxonomy"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "Get\u0020the\u0020instance.",
            "url": "classes/Clarkson-Core-Objects.html#method_get_instance"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003A__wakeup\u0028\u0029",
            "name": "__wakeup",
            "summary": "Wakeup.",
            "url": "classes/Clarkson-Core-Objects.html#method___wakeup"
        },                {
            "fqsen": "\\Clarkson_Core\\Objects\u003A\u003AOBJECT_CLASS_NAMESPACE",
            "name": "OBJECT_CLASS_NAMESPACE",
            "summary": "",
            "url": "classes/Clarkson-Core-Objects.html#constant_OBJECT_CLASS_NAMESPACE"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context",
            "name": "Template_Context",
            "summary": "",
            "url": "classes/Clarkson-Core-Template-Context.html"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aregister_hooks\u0028\u0029",
            "name": "register_hooks",
            "summary": "Register\u0020all\u0020hooks\u0020to\u0020add\u0020context\u0020to\u0020the\u0020template\u0020call.",
            "url": "classes/Clarkson-Core-Template-Context.html#method_register_hooks"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aadd_author\u0028\u0029",
            "name": "add_author",
            "summary": "Adds\u0020an\u0020author\u0020object\u0020if\u0020the\u0020current\u0020request\u0020is\u0020an\u0020author\u0020archive.",
            "url": "classes/Clarkson-Core-Template-Context.html#method_add_author"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aadd_term\u0028\u0029",
            "name": "add_term",
            "summary": "Adds\u0020a\u0020term\u0020if\u0020the\u0020current\u0020request\u0020is\u0020a\u0020term\u0020archive.",
            "url": "classes/Clarkson-Core-Template-Context.html#method_add_term"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aadd_search_count\u0028\u0029",
            "name": "add_search_count",
            "summary": "Adds\u0020the\u0020search\u0020result\u0020count\u0020if\u0020the\u0020current\u0020request\u0020is\u0020a\u0020search.",
            "url": "classes/Clarkson-Core-Template-Context.html#method_add_search_count"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aadd_posts\u0028\u0029",
            "name": "add_posts",
            "summary": "Adds\u0020posts\u0020to\u0020the\u0020current\u0020context.",
            "url": "classes/Clarkson-Core-Template-Context.html#method_add_posts"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aadd_post_type\u0028\u0029",
            "name": "add_post_type",
            "summary": "",
            "url": "classes/Clarkson-Core-Template-Context.html#method_add_post_type"
        },                {
            "fqsen": "\\Clarkson_Core\\Template_Context\u003A\u003Aadd_posts_page\u0028\u0029",
            "name": "add_posts_page",
            "summary": "Adds\u0020posts\u0020page\u0020overview\u0020as\u0020Clarkson\u0020Object\u0020if\u0020current\u0020page\u0020is\u0020home",
            "url": "classes/Clarkson-Core-Template-Context.html#method_add_posts_page"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates",
            "name": "Templates",
            "summary": "Allows\u0020rendering\u0020of\u0020specific\u0020templates\u0020with\u0020Twig.",
            "url": "classes/Clarkson-Core-Templates.html"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Arender_twig\u0028\u0029",
            "name": "render_twig",
            "summary": "Render\u0020template\u0020using\u0020Twig.",
            "url": "classes/Clarkson-Core-Templates.html#method_render_twig"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Aecho_twig\u0028\u0029",
            "name": "echo_twig",
            "summary": "Echo\u0020template.",
            "url": "classes/Clarkson-Core-Templates.html#method_echo_twig"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Aget_templates_dirs\u0028\u0029",
            "name": "get_templates_dirs",
            "summary": "Get\u0020the\u0020template\u0020directories\u0020where\u0020the\u0020Twig\u0020files\u0020are\u0020located\u0020in.",
            "url": "classes/Clarkson-Core-Templates.html#method_get_templates_dirs"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Aget_template_dir\u0028\u0029",
            "name": "get_template_dir",
            "summary": "Retrieves\u0020the\u0020parent\u0020theme\u0020directory\u0020Clarkson\u0020Core\u0020is\u0020using\u0020to\u0020find\u0020templates.",
            "url": "classes/Clarkson-Core-Templates.html#method_get_template_dir"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Aget_stylesheet_dir\u0028\u0029",
            "name": "get_stylesheet_dir",
            "summary": "Gets\u0020the\u0020stylesheet\u0020directory\u0020Clarkson\u0020Core\u0020is\u0020using\u0020to\u0020find\u0020twig\u0020templates.",
            "url": "classes/Clarkson-Core-Templates.html#method_get_stylesheet_dir"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "Get\u0020instance.",
            "url": "classes/Clarkson-Core-Templates.html#method_get_instance"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003Aadd_twig_to_template_hierarchy\u0028\u0029",
            "name": "add_twig_to_template_hierarchy",
            "summary": "",
            "url": "classes/Clarkson-Core-Templates.html#method_add_twig_to_template_hierarchy"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003A__wakeup\u0028\u0029",
            "name": "__wakeup",
            "summary": "Wakeup.",
            "url": "classes/Clarkson-Core-Templates.html#method___wakeup"
        },                {
            "fqsen": "\\Clarkson_Core\\Templates\u003A\u003A\u0024template_context",
            "name": "template_context",
            "summary": "The\u0020template\u0020context\u0020generator.",
            "url": "classes/Clarkson-Core-Templates.html#property_template_context"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object",
            "name": "Clarkson_Object",
            "summary": "Object\u0020oriented\u0020implementation\u0020of\u0020WordPress\u0020post\u0020objects.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Clarkson_Object\u0020constructor.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Check\u0020if\u0020name\u0020is\u0020not\u0020a\u0020wp_post\u0020object\u0020property.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method___get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_object\u0028\u0029",
            "name": "get_object",
            "summary": "Get\u0020the\u0020WordPress\u0020post\u0020object.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_object"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Clarkson\u0020Object\u0020for\u0020a\u0020WP_Post\u0020by\u0020ID.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020multiple\u0020posts,\u0020without\u0020pagination.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_one\u0028\u0029",
            "name": "get_one",
            "summary": "Gets\u0020the\u0020first\u0020result\u0020from\u0020a\u0020\u0060\u003A\u003Aget_many\u0028\u0029\u0060\u0020query.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_one"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_id\u0028\u0029",
            "name": "get_id",
            "summary": "Get\u0020the\u0020id\u0020of\u0020a\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_template\u0028\u0029",
            "name": "get_template",
            "summary": "",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_template"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_parent\u0028\u0029",
            "name": "get_parent",
            "summary": "Get\u0020the\u0020parent\u0020of\u0020the\u0020post,\u0020if\u0020any.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_parent"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_children\u0028\u0029",
            "name": "get_children",
            "summary": "Get\u0020the\u0020children\u0020of\u0020the\u0020post\u0020by\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_children"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_attachments\u0028\u0029",
            "name": "get_attachments",
            "summary": "Get\u0020the\u0020attachments\u0020for\u0020the\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_attachments"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Ahas_thumbnail\u0028\u0029",
            "name": "has_thumbnail",
            "summary": "Check\u0020if\u0020the\u0020post\u0020has\u0020a\u0020thumbnail.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_has_thumbnail"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_thumbnail\u0028\u0029",
            "name": "get_thumbnail",
            "summary": "Get\u0020the\u0020thumbnail\u0020HTML\u0020for\u0020the\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_thumbnail"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_thumbnail_id\u0028\u0029",
            "name": "get_thumbnail_id",
            "summary": "Get\u0020the\u0020thumbnail\u0020id\u0020by\u0020post\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_thumbnail_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_date\u0028\u0029",
            "name": "get_date",
            "summary": "Get\u0020the\u0020date\u0020the\u0020post\u0020was\u0020created\u0020in\u0020post_date_gmt\u0020format.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_date"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_date_i18n\u0028\u0029",
            "name": "get_date_i18n",
            "summary": "Get\u0020the\u0020date\u0020in\u0020localized\u0020format.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_date_i18n"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aset_date\u0028\u0029",
            "name": "set_date",
            "summary": "Set\u0020the\u0020post\u0020date\/time\u0020of\u0020the\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_set_date"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_local_date\u0028\u0029",
            "name": "get_local_date",
            "summary": "Get\u0020the\u0020local\u0020date\u0020the\u0020post\u0020was\u0020created.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_local_date"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_meta\u0028\u0029",
            "name": "get_meta",
            "summary": "Proxy\u0020for\u0020get_post_meta.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aupdate_meta\u0028\u0029",
            "name": "update_meta",
            "summary": "Update\u0020the\u0020post\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_update_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aadd_meta\u0028\u0029",
            "name": "add_meta",
            "summary": "Add\u0020post\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_add_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Adelete_meta\u0028\u0029",
            "name": "delete_meta",
            "summary": "Delete\u0020post\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_delete_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_delete"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_title\u0028\u0029",
            "name": "get_title",
            "summary": "Get\u0020the\u0020title\u0020of\u0020a\u0020post\u0020by\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_title"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_post_name\u0028\u0029",
            "name": "get_post_name",
            "summary": "Get\u0020post\u0020name\u0020\u0028slug\u0029\u0020by\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_post_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_content\u0028\u0029",
            "name": "get_content",
            "summary": "Get\u0020the\u0020post\u0020content.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_content"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_raw_content\u0028\u0029",
            "name": "get_raw_content",
            "summary": "Get\u0020the\u0020raw\u0020post\u0020content.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_raw_content"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_author_id\u0028\u0029",
            "name": "get_author_id",
            "summary": "Get\u0020the\u0020post\u0020author\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_author_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_author\u0028\u0029",
            "name": "get_author",
            "summary": "Get\u0020the\u0020post\u0020author\u0020object.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_author"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_permalink\u0028\u0029",
            "name": "get_permalink",
            "summary": "Get\u0020the\u0020post\u0020permalink.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_permalink"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_excerpt\u0028\u0029",
            "name": "get_excerpt",
            "summary": "Get\u0020the\u0020post\u0020excerpt.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_excerpt"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_post_type\u0028\u0029",
            "name": "get_post_type",
            "summary": "Get\u0020the\u0020post\u0027s\u0020post\u0020type.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_post_type"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_post_type_object\u0028\u0029",
            "name": "get_post_type_object",
            "summary": "Get\u0020the\u0020post\u0027s\u0020post\u0020type\u0020object.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_post_type_object"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_status\u0028\u0029",
            "name": "get_status",
            "summary": "Get\u0020the\u0020post\u0027s\u0020post\u0020status.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_status"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aset_status\u0028\u0029",
            "name": "set_status",
            "summary": "Update\u0020the\u0020posts\u0020status.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_set_status"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aadd_comment\u0028\u0029",
            "name": "add_comment",
            "summary": "Add\u0020post\u0020comment.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_add_comment"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aget_terms\u0028\u0029",
            "name": "get_terms",
            "summary": "Retrieve\u0020the\u0020terms\u0020for\u0020a\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_get_terms"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aadd_term\u0028\u0029",
            "name": "add_term",
            "summary": "Add\u0020a\u0020single\u0020term\u0020to\u0020a\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_add_term"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aadd_terms\u0028\u0029",
            "name": "add_terms",
            "summary": "Bulk\u0020add\u0020terms\u0020to\u0020a\u0020post.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_add_terms"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Areset_terms\u0028\u0029",
            "name": "reset_terms",
            "summary": "Reset\u0020terms.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_reset_terms"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Aremove_term\u0028\u0029",
            "name": "remove_term",
            "summary": "Remove\u0020a\u0020post\u0020term.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_remove_term"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003Ahas_term\u0028\u0029",
            "name": "has_term",
            "summary": "Is\u0020post\u0020associated\u0020with\u0020term\u003F",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_has_term"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "Return\u0020a\u0020set\u0020of\u0020data\u0020to\u0020use\u0020for\u0020json\u0020output.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Object\u003A\u003A\u0024type",
            "name": "type",
            "summary": "The\u0020string\u0020here\u0020is\u0020the\u0020post\u0020type\u0020name\u0020used\u0020by\u0020\u0060\u003A\u003Aget_many\u0028\u0029\u0060.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Object.html#property_type"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type",
            "name": "Clarkson_Post_Type",
            "summary": "Clarkson\u0020Post\u0020Type\u0020class.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020post\u0020type\u0020object\u0020by\u0020post\u0020type\u0020name",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020all\u0020available\u0020Clarkson\u0020Post\u0020Type\u0020objects",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Proxy\u0020requested\u0020properties\u0020to\u0020WP\u0020Post\u0020Type\u0020if\u0020it\u0020doesn\u0027t\u0020exist\u0020in\u0020Clarkson\u0020Post\u0020Type",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method___get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_posts\u0028\u0029",
            "name": "get_posts",
            "summary": "Get\u0020multiple\u0020posts,\u0020without\u0020pagination.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_posts"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "Exists\u0020check\u0020for\u0020__get\u0020function",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method___isset"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_title\u0028\u0029",
            "name": "get_title",
            "summary": "Get\u0020the\u0020post\u0020type\u0020title.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_title"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_post_type\u0028\u0029",
            "name": "get_post_type",
            "summary": "Get\u0020the\u0020post\u0020type\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_post_type"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_archive_title\u0028\u0029",
            "name": "get_archive_title",
            "summary": "Get\u0020the\u0020post\u0020type\u0020archive\u0020title.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_archive_title"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_archive_permalink\u0028\u0029",
            "name": "get_archive_permalink",
            "summary": "Get\u0020the\u0020archive\u0020permalink.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_archive_permalink"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Post_Type\u003A\u003Aget_archive_feed_permalink\u0028\u0029",
            "name": "get_archive_feed_permalink",
            "summary": "Get\u0020the\u0020archive\u0020feed\u0020permalink.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Post-Type.html#method_get_archive_feed_permalink"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Role",
            "name": "Clarkson_Role",
            "summary": "Object\u0020oriented\u0020wrapper\u0020for\u0020WP_Role\u0020objects.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Role.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Role\u003A\u003Aget_by_name\u0028\u0029",
            "name": "get_by_name",
            "summary": "Get\u0020Clarkson\u0020Role\u0020object\u0020by\u0020role\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Role.html#method_get_by_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Role\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020Clarkson\u0020Role\u0020object\u0020by\u0020role\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Role.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Role\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020all\u0020available\u0020Clarkson\u0020Role\u0020objects",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Role.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Role\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Clarkson_Role\u0020constructor.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Role.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Role\u003A\u003Aget_role\u0028\u0029",
            "name": "get_role",
            "summary": "Get\u0020the\u0020WordPress\u0020WP_Role\u0020object.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Role.html#method_get_role"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy",
            "name": "Clarkson_Taxonomy",
            "summary": "Clarkson\u0020Taxonomy\u0020class.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020taxonomy\u0020object\u0020by\u0020taxonomy\u0020name",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020all\u0020available\u0020Clarkson\u0020Taxonomy\u0020objects",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Proxy\u0020requested\u0020properties\u0020to\u0020Taxonomy\u0020if\u0020it\u0020doesn\u0027t\u0020exist\u0020in\u0020Clarkson\u0020Taxonomy",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method___get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "Exists\u0020check\u0020for\u0020__get\u0020function",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method___isset"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003Aget_taxonomy\u0028\u0029",
            "name": "get_taxonomy",
            "summary": "Get\u0020the\u0020taxonomy\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method_get_taxonomy"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003Aget_title\u0028\u0029",
            "name": "get_title",
            "summary": "Get\u0020the\u0020taxonomy\u0020title.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method_get_title"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003Aget_terms\u0028\u0029",
            "name": "get_terms",
            "summary": "Get\u0020multiple\u0020terms.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method_get_terms"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Taxonomy\u003A\u003Aget_supported_post_types\u0028\u0029",
            "name": "get_supported_post_types",
            "summary": "Get\u0020the\u0020post\u0020type\u0020names\u0020that\u0020support\u0020this\u0020taxonomy.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Taxonomy.html#method_get_supported_post_types"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template",
            "name": "Clarkson_Template",
            "summary": "",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020multiple\u0020templates,\u0020without\u0020pagination.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template\u003A\u003Aget_one\u0028\u0029",
            "name": "get_one",
            "summary": "Gets\u0020the\u0020first\u0020result\u0020from\u0020a\u0020\u0060\u003A\u003Aget_many\u0028\u0029\u0060\u0020query.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html#method_get_one"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template\u003A\u003Aget_object\u0028\u0029",
            "name": "get_object",
            "summary": "Get\u0020the\u0020Clarkson\u0020object\u0020for\u0020this\u0020template.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html#method_get_object"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Template\u003A\u003A\u0024type",
            "name": "type",
            "summary": "The\u0020string\u0020here\u0020is\u0020the\u0020template\u0020name\u0020used\u0020by\u0020\u0060\u003A\u003Aget_many\u0028\u0029\u0060.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Template.html#property_type"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term",
            "name": "Clarkson_Term",
            "summary": "Object\u0020oriented\u0020wrapper\u0020for\u0020WP_Term\u0020objects.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_by_name\u0028\u0029",
            "name": "get_by_name",
            "summary": "Get\u0020term\u0020by\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_by_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_by_slug\u0028\u0029",
            "name": "get_by_slug",
            "summary": "Get\u0020term\u0020by\u0020slug.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_by_slug"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_by_id\u0028\u0029",
            "name": "get_by_id",
            "summary": "Get\u0020term\u0020by\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_by_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Alias\u0020of\u0020\u0060get_by_id\u0028\u0029\u0060.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020multiple\u0020terms\u0020as\u0020Clarkson\u0020Objects.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_one\u0028\u0029",
            "name": "get_one",
            "summary": "Gets\u0020the\u0020first\u0020result\u0020from\u0020a\u0020\u0060\u003A\u003Aget_many\u0028\u0029\u0060\u0020query.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_one"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Clarkson_Term\u0020constructor.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Check\u0020if\u0020an\u0020existing\u0020field\u0020is\u0020requested.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method___get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Ais_queried_object\u0028\u0029",
            "name": "is_queried_object",
            "summary": "Check\u0020if\u0020this\u0020term\u0020was\u0020used\u0020in\u0020the\u0020global\u0020\u0024wp_query.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_is_queried_object"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_id\u0028\u0029",
            "name": "get_id",
            "summary": "Get\u0020the\u0020id\u0020of\u0020the\u0020term.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_parent\u0028\u0029",
            "name": "get_parent",
            "summary": "Get\u0020the\u0020term\u0020parent.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_parent"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_taxonomy\u0028\u0029",
            "name": "get_taxonomy",
            "summary": "Get\u0020the\u0020taxonomy.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_taxonomy"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_taxonomy_object\u0028\u0029",
            "name": "get_taxonomy_object",
            "summary": "Get\u0020the\u0020term\u0027s\u0020taxonomy\u0020object.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_taxonomy_object"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_meta\u0028\u0029",
            "name": "get_meta",
            "summary": "Get\u0020term\u0020meta\u0020data\u0020by\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aupdate_meta\u0028\u0029",
            "name": "update_meta",
            "summary": "Update\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_update_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aadd_meta\u0028\u0029",
            "name": "add_meta",
            "summary": "Update\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_add_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Adelete_meta\u0028\u0029",
            "name": "delete_meta",
            "summary": "Delete\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_delete_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_slug\u0028\u0029",
            "name": "get_slug",
            "summary": "Get\u0020the\u0020term\u0020slug.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_slug"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "Get\u0020the\u0020term\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_description\u0028\u0029",
            "name": "get_description",
            "summary": "Get\u0020the\u0020term\u0020description.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_description"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aset_name\u0028\u0029",
            "name": "set_name",
            "summary": "Update\u0020term\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_set_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_term\u0028\u0029",
            "name": "get_term",
            "summary": "Get\u0020the\u0020term\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_term"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_term_taxonomy_id\u0028\u0029",
            "name": "get_term_taxonomy_id",
            "summary": "Get\u0020the\u0020taxonomy\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_term_taxonomy_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_Term\u003A\u003Aget_permalink\u0028\u0029",
            "name": "get_permalink",
            "summary": "Get\u0020the\u0020term\u0020permalink.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-Term.html#method_get_permalink"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User",
            "name": "Clarkson_User",
            "summary": "Object\u0020oriented\u0020wrapper\u0020for\u0020WP_User\u0020objects.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Acurrent_user\u0028\u0029",
            "name": "current_user",
            "summary": "Get\u0020the\u0020current\u0020logged\u0020in\u0020user.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_current_user"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020user\u0020data\u0020by\u0020user\u0020id.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_many\u0028\u0029",
            "name": "get_many",
            "summary": "Get\u0020multiple\u0020users\u0020as\u0020Clarkson\u0020users.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_many"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_one\u0028\u0029",
            "name": "get_one",
            "summary": "Gets\u0020the\u0020first\u0020result\u0020from\u0020a\u0020\u0060\u003A\u003Aget_many\u0028\u0029\u0060\u0020query.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_one"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Clarkson_User\u0020constructor.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method___construct"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Ais_current_user\u0028\u0029",
            "name": "is_current_user",
            "summary": "Check\u0020if\u0020this\u0020user\u0020is\u0020the\u0020currently\u0020logged\u0020in\u0020user.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_is_current_user"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_user\u0028\u0029",
            "name": "get_user",
            "summary": "Get\u0020the\u0020WordPress\u0020WP_User\u0020object.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_user"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_id\u0028\u0029",
            "name": "get_id",
            "summary": "Get\u0020the\u0020ID\u0020of\u0020the\u0020user.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_id"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_display_name\u0028\u0029",
            "name": "get_display_name",
            "summary": "Get\u0020the\u0020display\u0020name\u0020of\u0020the\u0020user.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_display_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_display_first_name\u0028\u0029",
            "name": "get_display_first_name",
            "summary": "Get\u0020the\u0020user\u0027s\u0020first\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_display_first_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_display_last_name\u0028\u0029",
            "name": "get_display_last_name",
            "summary": "Get\u0020the\u0020user\u0027s\u0020last\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_display_last_name"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_email\u0028\u0029",
            "name": "get_email",
            "summary": "Get\u0020the\u0020user\u0027s\u0020email\u0020address.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_email"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_login\u0028\u0029",
            "name": "get_login",
            "summary": "Get\u0020the\u0020user\u0027s\u0020login\u0020name.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_login"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_roles\u0028\u0029",
            "name": "get_roles",
            "summary": "Get\u0020the\u0020user\u0027s\u0020roles.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_roles"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_role_objects\u0028\u0029",
            "name": "get_role_objects",
            "summary": "Get\u0020the\u0020user\u0027s\u0020role\u0020objects.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_role_objects"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aget_meta\u0028\u0029",
            "name": "get_meta",
            "summary": "Get\u0020the\u0020user\u0027s\u0020user_meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_get_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aupdate_meta\u0028\u0029",
            "name": "update_meta",
            "summary": "Update\u0020user\u0020meta\u0020data.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_update_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Aadd_meta\u0028\u0029",
            "name": "add_meta",
            "summary": "Add\u0020a\u0020meta\u0020key\u003D\u003Evalue\u0020for\u0020the\u0020user.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_add_meta"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object\\Clarkson_User\u003A\u003Adelete_meta\u0028\u0029",
            "name": "delete_meta",
            "summary": "Delete\u0020a\u0020meta\u0020key\u003D\u003Evalue\u0020for\u0020the\u0020user.",
            "url": "classes/Clarkson-Core-WordPress-Object-Clarkson-User.html#method_delete_meta"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Clarkson_Core",
            "name": "Clarkson_Core",
            "summary": "",
            "url": "namespaces/clarkson-core.html"
        },                {
            "fqsen": "\\Clarkson_Core\\Gutenberg",
            "name": "Gutenberg",
            "summary": "",
            "url": "namespaces/clarkson-core-gutenberg.html"
        },                {
            "fqsen": "\\Clarkson_Core\\WordPress_Object",
            "name": "WordPress_Object",
            "summary": "",
            "url": "namespaces/clarkson-core-wordpress-object.html"
        }            ]
);
