name: Test
on: [push]

jobs:
  build:
    strategy:
      matrix:
        php: ['7.4']
      fail-fast: false
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install PHP and enable required extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: simplexml

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version

    - name: Install dependencies
      run: |
        composer install --prefer-dist

    - name: Run tests
      run: composer run test
